Repository AY2122S2-CS2113T-T09-2/tp, pull requests merged in 2022-03, with the labels that each got.

#30 Added input validation for listing the workouts method
  src/main/java/Main.java
  src/main/java/commands/Command.java
  src/main/java/commands/HelpCommand.java
  src/main/java/commands/WorkoutCommand.java
  src/main/java/data/exercises/ExerciseList.java
  src/main/java/data/workouts/InvalidWorkoutException.java
  src/main/java/data/workouts/WorkoutList.java
  src/main/java/data/workouts/WorkoutOutOfRangeException.java
  src/main/java/werkit/Parser.java
  src/main/java/werkit/UI.java
  src/main/java/werkit/WerkIt.java
  src/test/java/werkit/WerkItTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, severity.Medium

#35 Input validation check for list feature
  src/main/java/commands/InvalidCommandException.java
  src/main/java/data/workouts/WorkoutList.java
  src/main/java/werkit/Parser.java
  werkItResources/workouts.txt
Labels: type.Bug, severity.Low

#58 Branch user guide for list workout
  docs/UserGuide.md
  src/main/java/data/workouts/WorkoutList.java
  src/test/java/data/workouts/WorkoutListTest.java
  werkItResources/workouts.txt
Labels: documentation

#101 Update UG with 'help' and 'exercise /list' commands
  docs/UserGuide.md
Labels: documentation

#105 Schedule update feature
  src/main/java/commands/InvalidCommandException.java
  src/main/java/commands/ScheduleCommand.java
  src/main/java/data/schedule/Day.java
  src/main/java/data/schedule/DayList.java
  src/main/java/data/schedule/InvalidScheduleException.java
  src/main/java/werkit/Parser.java
  src/main/java/werkit/UI.java
  src/main/java/werkit/WerkIt.java
  src/test/java/werkit/ParserTest.java
  werkItResources/workouts.txt
Labels: type.Task, priority.High

#106 Implement view schedule feature
  src/main/java/commands/ScheduleCommand.java
  src/main/java/data/schedule/DayList.java
  src/main/java/data/schedule/InvalidScheduleException.java
  src/main/java/werkit/Parser.java
  src/main/java/werkit/UI.java
  werkItResources/workouts.txt
Labels: type.Task, priority.High

#107 Implement clear schedule feature
  src/main/java/commands/ScheduleCommand.java
  src/main/java/data/schedule/DayList.java
  src/main/java/werkit/UI.java
Labels: type.Task, priority.High

#110 Branch dg1
  docs/DeveloperGuide.md
  docs/uml/Search.puml
  docs/uml/diagram/SearchClassUML.png
Labels: documentation

#117 Add user guide for schedule features
  docs/UserGuide.md
  src/main/java/werkit/UI.java
Labels: documentation

#125 Workout listall feature
  src/main/java/commands/InvalidCommandException.java
  src/main/java/commands/WorkoutCommand.java
  src/main/java/data/workouts/WorkoutList.java
  src/main/java/werkit/Parser.java
Labels: type.Task, priority.Medium

#127 Javadoc for schedule features
  docs/UserGuide.md
  src/main/java/commands/ScheduleCommand.java
  src/main/java/data/schedule/Day.java
  src/main/java/data/schedule/DayList.java
Labels: documentation

#131 DeveloperGuide.md: Fix broken code block
  docs/DeveloperGuide.md
Labels: type.Bug, documentation, severity.Low

#135 Fix rendering issue for delete workout DG
  docs/DeveloperGuide.md
Labels: type.Bug

#138 Enhance check for valid plan name
  docs/uml/sequenceDiagrams/createAndAddPlan.puml
  docs/uml/sequenceDiagrams/images/createAndAddPlan.png
  src/main/java/data/plans/InvalidPlanException.java
  src/main/java/data/plans/PlanList.java
  src/test/java/data/plans/PlanListTest.java
Labels: type.Enhancement

#140 Addition of details to user guide
  docs/UserGuide.md
  src/main/java/commands/SearchCommand.java
  src/main/java/storage/FileManager.java
  src/main/java/werkit/Parser.java
  src/main/java/werkit/UI.java
  src/main/java/werkit/WerkIt.java
Labels: documentation

#142 Fix bug related to an issue with loading of schedule data from file
  src/main/java/data/plans/InvalidPlanException.java
  src/main/java/data/plans/PlanList.java
  src/main/java/storage/FileManager.java
  src/main/java/werkit/WerkIt.java
  src/test/java/commands/WorkoutCommandTest.java
  src/test/java/storage/FileManagerTest.java
Labels: type.Bug, severity.High

#151 Fix list markdown
  docs/UserGuide.md
Labels: type.Bug

#153 Fix bug related to Plan Details
  src/main/java/data/plans/PlanList.java
Labels: type.Bug

#155 Branch dg sequence
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/images/searchAll.png
  docs/uml/sequenceDiagrams/images/searchExercise.png
  docs/uml/sequenceDiagrams/images/searchPlan.png
  docs/uml/sequenceDiagrams/images/searchWorkout.png
  docs/uml/sequenceDiagrams/images/viewExercise.png
  docs/uml/sequenceDiagrams/searchAll.puml
  docs/uml/sequenceDiagrams/searchExercise.puml
  docs/uml/sequenceDiagrams/searchPlan.puml
  docs/uml/sequenceDiagrams/searchWorkout.puml
  docs/uml/sequenceDiagrams/viewExercise.puml
Labels: documentation

#164 Add more contents to DG
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/createAndAddPlan.puml
  docs/uml/sequenceDiagrams/createPlan-Part1.puml
  docs/uml/sequenceDiagrams/createPlan-Part2.puml
  docs/uml/sequenceDiagrams/deleteWorkout-Part1.puml
  docs/uml/sequenceDiagrams/deleteWorkout-Part2.puml
  docs/uml/sequenceDiagrams/images/createAndAddPlan.png
  docs/uml/sequenceDiagrams/images/createPlan-Part1.png
  docs/uml/sequenceDiagrams/images/createPlan-Part2.png
  docs/uml/sequenceDiagrams/images/deleteWorkout-Part1.png
  docs/uml/sequenceDiagrams/images/deleteWorkout-Part2.png
  docs/uml/sequenceDiagrams/images/deleteWorkout.png
  docs/uml/sequenceDiagrams/images/deleteWorkoutDetailed.png
  docs/uml/sequenceDiagrams/images/listPlan.png
  docs/uml/sequenceDiagrams/listPlan.puml
  src/main/java/data/plans/PlanList.java
Labels: documentation

#166 Fixed schedule clear bug
  src/main/java/commands/ScheduleCommand.java
Labels: type.Bug, severity.High

#167 Simplify sequence diagram
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/createPlan-Part2.puml
  docs/uml/sequenceDiagrams/deleteWorkout-Part2.puml
  docs/uml/sequenceDiagrams/images/createPlan-Part2.png
  docs/uml/sequenceDiagrams/images/deleteWorkout-Part2.png
Labels: documentation

#168 Update DG for schedule features documentation
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/clearAllSchedule.puml
  docs/uml/sequenceDiagrams/clearSchedule.puml
  docs/uml/sequenceDiagrams/images/clearAllSchedule.png
  docs/uml/sequenceDiagrams/images/clearSchedule.png
  docs/uml/sequenceDiagrams/images/listSchedule.png
  docs/uml/sequenceDiagrams/images/updateSchedule.png
  docs/uml/sequenceDiagrams/images/updateScheduleDetails.png
  docs/uml/sequenceDiagrams/updateSchedule.puml
  docs/uml/sequenceDiagrams/updateScheduleDetails.puml
  docs/uml/sequenceDiagrams/viewSchedule.puml
Labels: documentation

#171 Add design DG for search related feature
  docs/DeveloperGuide.md
Labels: documentation

#174 UserGuide.md: Update UG on Colour Display Issue
  docs/UserGuide.md
Labels: documentation

#176 Reorganise Sequence Diagrams in Project Directory
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/exercises/images/viewExercise.png
  docs/uml/sequenceDiagrams/exercises/viewExercise.puml
  docs/uml/sequenceDiagrams/plans/createPlan-Part1.puml
  docs/uml/sequenceDiagrams/plans/createPlan-Part2.puml
  docs/uml/sequenceDiagrams/plans/images/createPlan-Part1.png
  docs/uml/sequenceDiagrams/plans/images/createPlan-Part2.png
  docs/uml/sequenceDiagrams/plans/images/listPlan.png
  docs/uml/sequenceDiagrams/plans/listPlan.puml
  docs/uml/sequenceDiagrams/schedule/clearAllSchedule.puml
  docs/uml/sequenceDiagrams/schedule/clearSchedule.puml
  docs/uml/sequenceDiagrams/schedule/images/clearAllSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/clearSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/listSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/updateSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/updateScheduleDetails.png
  docs/uml/sequenceDiagrams/schedule/updateSchedule.puml
  docs/uml/sequenceDiagrams/schedule/updateScheduleDetails.puml
  docs/uml/sequenceDiagrams/schedule/viewSchedule.puml
  docs/uml/sequenceDiagrams/search/images/searchAll.png
  docs/uml/sequenceDiagrams/search/images/searchExercise.png
  docs/uml/sequenceDiagrams/search/images/searchPlan.png
  docs/uml/sequenceDiagrams/search/images/searchWorkout.png
  docs/uml/sequenceDiagrams/search/searchAll.puml
  docs/uml/sequenceDiagrams/search/searchExercise.puml
  docs/uml/sequenceDiagrams/search/searchPlan.puml
  docs/uml/sequenceDiagrams/search/searchWorkout.puml
  docs/uml/sequenceDiagrams/workouts/CreateAndAddWorkout-Part1.puml
  docs/uml/sequenceDiagrams/workouts/CreateAndAddWorkout-Part2.puml
  docs/uml/sequenceDiagrams/workouts/CreateWorkout-obtainUI.puml
  docs/uml/sequenceDiagrams/workouts/CreateWorkout.puml
  docs/uml/sequenceDiagrams/workouts/deleteWorkout-Part1.puml
  docs/uml/sequenceDiagrams/workouts/deleteWorkout-Part2.puml
  docs/uml/sequenceDiagrams/workouts/images/CreateAndAddWorkout-Part1.png
  docs/uml/sequenceDiagrams/workouts/images/CreateAndAddWorkout-Part2.png
  docs/uml/sequenceDiagrams/workouts/images/CreateWorkout.png
  docs/uml/sequenceDiagrams/workouts/images/deleteWorkout-Part1.png
  docs/uml/sequenceDiagrams/workouts/images/deleteWorkout-Part2.png
Labels: documentation, type.Enhancement

#177 DG: Improve Write-Up of `workout /new` Implementation
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/miscellaneous/obtainAndParseUserInput.puml
  docs/uml/sequenceDiagrams/workouts/CreateAndAddWorkout-Part1.puml
  docs/uml/sequenceDiagrams/workouts/CreateAndAddWorkout.puml
  docs/uml/sequenceDiagrams/workouts/CreateWorkout.puml
  docs/uml/sequenceDiagrams/workouts/images/CreateAndAddWorkout-Part1.png
  docs/uml/sequenceDiagrams/workouts/images/CreateAndAddWorkout-Part2.png
  docs/uml/sequenceDiagrams/workouts/images/CreateAndAddWorkout.png
  docs/uml/sequenceDiagrams/workouts/images/CreateWorkout.png
Labels: documentation
