Repository AY2122S2-CS2113T-T09-2/tp, pull requests merged in 2022-04, with the labels that each got.

#180 Improve DG based on peer feedback tutorial
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/plans/createPlan-Part1.puml
  docs/uml/sequenceDiagrams/plans/createPlan-Part2.puml
  docs/uml/sequenceDiagrams/plans/images/createPlan-Part1.png
  docs/uml/sequenceDiagrams/plans/images/createPlan-Part2.png
  docs/uml/sequenceDiagrams/plans/images/listPlan.png
  docs/uml/sequenceDiagrams/plans/listPlan.puml
  docs/uml/sequenceDiagrams/workouts/deleteWorkout-Part1.puml
  docs/uml/sequenceDiagrams/workouts/deleteWorkout-Part2.puml
  docs/uml/sequenceDiagrams/workouts/images/deleteWorkout-Part1.png
  docs/uml/sequenceDiagrams/workouts/images/deleteWorkout-Part2.png
Labels: documentation

#178 Create CSS Stylesheet for GitHub Pages Docs
  docs/DeveloperGuide.md
  docs/_config.yml
  docs/assets/css/style.scss
Labels: documentation, type.Enhancement

#181 Edits to dg
  docs/DeveloperGuide.md
  docs/high-level-diagram/architecture-diagram.puml
  docs/high-level-diagram/architecture_diagram.png
  docs/uml/sequenceDiagrams/schedule/clearAllSchedule.puml
  docs/uml/sequenceDiagrams/schedule/clearSchedule.puml
  docs/uml/sequenceDiagrams/schedule/images/clearAllSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/clearSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/listSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/updateSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/updateScheduleDetails.png
  docs/uml/sequenceDiagrams/schedule/updateSchedule.puml
  docs/uml/sequenceDiagrams/schedule/updateScheduleDetails.puml
  docs/uml/sequenceDiagrams/schedule/viewSchedule.puml
  docs/uml/sequenceDiagrams/workouts/images/listWorkout.png
  docs/uml/sequenceDiagrams/workouts/listWorkouts.puml
  src/main/java/commands/WorkoutCommand.java
  src/main/java/data/workouts/WorkoutList.java
  src/main/java/werkit/Parser.java
  src/test/java/data/workouts/WorkoutListTest.java
  src/test/java/werkit/ParserTest.java
Labels: documentation

#172 Improve Delete Workout feature
  src/main/java/commands/WorkoutCommand.java
  src/main/java/data/plans/PlanList.java
  src/main/java/data/workouts/WorkoutList.java
  src/test/java/data/plans/PlanListTest.java
  src/test/java/data/workouts/WorkoutListTest.java
Labels: type.Enhancement

#215 Branch update document
  docs/uml/classDiagrams/Search.puml
  docs/uml/classDiagrams/images/SearchClass.png
  docs/uml/sequenceDiagrams/exercises/viewExercise.puml
  docs/uml/sequenceDiagrams/search/images/searchAll.png
  docs/uml/sequenceDiagrams/search/images/searchExercise.png
  docs/uml/sequenceDiagrams/search/images/searchPlan.png
  docs/uml/sequenceDiagrams/search/images/searchWorkout.png
  docs/uml/sequenceDiagrams/search/searchAll.puml
  docs/uml/sequenceDiagrams/search/searchExercise.puml
  docs/uml/sequenceDiagrams/search/searchPlan.puml
  docs/uml/sequenceDiagrams/search/searchWorkout.puml
Labels: documentation

#218 Branch file bug
  src/main/java/commands/Command.java
  src/main/java/commands/ExerciseCommand.java
  src/main/java/commands/ExitCommand.java
  src/main/java/commands/HelpCommand.java
  src/main/java/data/schedule/DayList.java
  src/main/java/storage/FileManager.java
  src/main/java/werkit/WerkIt.java
Labels: type.Bug, severity.High

#217 Docs - Introduce Custom Warning and Info Boxes
  docs/DeveloperGuide.md
  docs/assets/css/style.scss
Labels: documentation, type.Enhancement

#221 New edits to ug after feedback from peers
  docs/UserGuide.md
  docs/images/exerciseList.png
  docs/images/planExplanation.png
  docs/images/planList.png
  docs/images/workoutExplanation.png
  docs/images/workoutList.png
Labels: documentation

#224 Edit to css in ug
  docs/UserGuide.md
Labels: documentation

#220 DG - Create Section on 'Obtaining and Parsing User Input'
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/miscellaneous/images/obtainAndParseUserInput.png
  docs/uml/sequenceDiagrams/miscellaneous/obtainAndParseUserInput.puml
  docs/uml/sequenceDiagrams/workouts/CreateAndAddWorkout.puml
  docs/uml/sequenceDiagrams/workouts/CreateWorkout.puml
  docs/uml/sequenceDiagrams/workouts/images/CreateAndAddWorkout.png
  docs/uml/sequenceDiagrams/workouts/images/CreateWorkout.png
Labels: documentation

#225 UG - Make Windows Terminal necessary for Windows Users
  docs/UserGuide.md
  docs/images/noWeirdSymbols.png
  docs/images/weirdSymbols-firstTimeRun.png
  docs/images/weirdSymbols-helpCommand.png
  docs/images/weirdSymbols-subsequentRuns.png
Labels: documentation

#223 Write DG for Update Workout
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/workouts/deleteWorkout-Part1.puml
  docs/uml/sequenceDiagrams/workouts/images/deleteWorkout-Part1.png
  docs/uml/sequenceDiagrams/workouts/images/updateWorkout-Part1.png
  docs/uml/sequenceDiagrams/workouts/images/updateWorkout-Part2.png
  docs/uml/sequenceDiagrams/workouts/updateWorkout-Part1.puml
  docs/uml/sequenceDiagrams/workouts/updateWorkout-Part2.puml
  src/main/java/commands/WorkoutCommand.java
  src/main/java/data/plans/PlanList.java
  src/main/java/data/workouts/WorkoutList.java
Labels: documentation

#226 PPP - Create Draft
  docs/AboutUs.md
  docs/assets/css/style.scss
  docs/images/ppp/alanlowzies/infoWarningBoxes.png
  docs/images/ppp/alanlowzies/pedBugReport.png
  docs/images/ppp/alanlowzies/tPCodeDashboard.png
  docs/team/alanlowzies.md
Labels: documentation

#234 Add junit testing for schedule features
  src/main/java/commands/InvalidCommandException.java
  src/test/java/commands/ScheduleCommandTest.java
  src/test/java/data/schedule/DayListTest.java
Labels: type.Task

#235 Add some parts of the PPP
  docs/images/ppp/musfirahe0556596/tpCodeDashboard.PNG
  docs/team/musfirahe0556596.md
  src/main/java/data/workouts/WorkoutList.java
Labels: documentation

#231 Make Changes to the UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_config.yml
  docs/team/alanlowzies.md
Labels: documentation

#237 Fixed schedule clear feature bug
  src/main/java/data/schedule/DayList.java
Labels: type.Task

#236 Add application flow diagram into ug
  docs/UserGuide.md
  docs/high-level-diagram/application_flow.png
  docs/high-level-diagram/application_flow_diagram.puml
Labels: documentation

#232 Add design consideration for Inconsistent Data Between Resource Files
  docs/DeveloperGuide.md
Labels: documentation

#233 Branch exercise design
  docs/DeveloperGuide.md
  docs/uml/classDiagrams/exercise.puml
  docs/uml/classDiagrams/images/exercise.png
Labels: documentation

#238 Add and split design writeup sections in DG
  docs/DeveloperGuide.md
  docs/high-level-diagram/architecture-diagram.puml
  docs/high-level-diagram/architecture_diagram.png
Labels: documentation

#241 Write up on ppp
  docs/UserGuide.md
  docs/images/ppp/emilysim00/severeBug1.png
  docs/images/ppp/emilysim00/tPCodeDashboard.png
  docs/team/emilysim00.md
  src/main/java/commands/ScheduleCommand.java
Labels: documentation

#246 Update UG
  docs/UserGuide.md
  docs/images/expectedMessageForDeletePlan.png
  docs/images/expectedMessageForUpdateWorkout.png
  src/main/java/storage/FileManager.java
Labels: documentation

#248 Branch fix search and file
  docs/DeveloperGuide.md
  src/main/java/commands/SearchCommand.java
  src/main/java/data/exercises/ExerciseList.java
  src/main/java/data/plans/PlanList.java
  src/main/java/data/workouts/WorkoutList.java
  src/main/java/storage/FileManager.java
  src/main/java/werkit/Parser.java
  src/main/java/werkit/WerkIt.java
  src/test/java/commands/PlanCommandTest.java
  src/test/java/data/plans/PlanListTest.java
  src/test/java/storage/FileManagerTest.java
  src/test/java/werkit/ParserTest.java
Labels: type.Bug

#252 Wrtie DG for viewing details of a plan
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/uml/sequenceDiagrams/plans/detailsOfPlan.puml
  docs/uml/sequenceDiagrams/plans/images/detailsOfPlan.png
Labels: documentation

#249 Documentation on design schedule feature in dg
  docs/DeveloperGuide.md
  docs/uml/classDiagrams/ScheduleClass.puml
  docs/uml/classDiagrams/images/scheduleComponent.png
Labels: documentation

#255 Edits to schedule plantuml diagram
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/schedule/clearAllSchedule.puml
  docs/uml/sequenceDiagrams/schedule/clearSchedule.puml
  docs/uml/sequenceDiagrams/schedule/images/clearAllSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/clearSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/listSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/updateSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/updateScheduleDetails.png
  docs/uml/sequenceDiagrams/schedule/updateSchedule.puml
  docs/uml/sequenceDiagrams/schedule/updateScheduleDetails.puml
  docs/uml/sequenceDiagrams/schedule/viewSchedule.puml
  src/main/java/commands/ScheduleCommand.java
  src/main/java/data/schedule/DayList.java
  src/main/java/werkit/UI.java
Labels: documentation

#253 Fix workout update UI issue
  src/main/java/data/plans/PlanList.java
Labels: type.Bug, priority.Medium, severity.Medium

#257 More DG writeup
  docs/DeveloperGuide.md
  docs/high-level-diagram/architecture-diagram.puml
  docs/high-level-diagram/architecture_diagram.png
  docs/uml/classDiagrams/images/logicComponent.png
  docs/uml/classDiagrams/logicComponent.puml
  docs/uml/sequenceDiagrams/miscellaneous/images/logicComponentSD.png
  docs/uml/sequenceDiagrams/miscellaneous/logicComponentSD.puml
Labels: documentation

#260 Branch dg parser
  docs/DeveloperGuide.md
  docs/team/a1021492980.md
  src/main/java/commands/InvalidCommandException.java
  src/main/java/werkit/Parser.java
Labels: type.Bug, documentation, severity.VeryLow

#261 Add DG and PPP writeups
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ppp/musfirahe0556596/PRReviews.PNG
  docs/images/ppp/musfirahe0556596/tpCommentDashboard.PNG
  docs/team/musfirahe0556596.md
Labels: documentation

#264 Edits to UG
  docs/UserGuide.md
  docs/images/expectedMessageForDeletePlan.png
  docs/images/workoutExplanation.png
Labels: documentation

#265 Write DG for architecture diagram
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/miscellaneous/ArchitectureSequenceDiagram.puml
  docs/uml/sequenceDiagrams/miscellaneous/images/ArchitectureSequenceDiagram.png
Labels: documentation

#267 Branch fix populate exercise
  src/main/java/data/exercises/ExerciseList.java
  src/main/java/werkit/WerkIt.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, severity.High

#269 Differentiate reps and rep
  src/main/java/data/workouts/Workout.java
Labels: severity.Low

#279 Ppp new edits
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/emilysim00.md
Labels: documentation

#285 Add Instruction for Manual Testing
  docs/DeveloperGuide.md
  docs/team/musfirahe0556596.md
Labels: documentation

#287 Add break lines to manual testing section
  docs/DeveloperGuide.md
Labels: documentation

#288 Branch improve dg
  docs/DeveloperGuide.md
  docs/uml/classDiagrams/images/workoutRelatedFeatures.png
  docs/uml/classDiagrams/workoutRelatedFeatures.puml
  docs/uml/sequenceDiagrams/plans/createPlan-Part1.puml
  docs/uml/sequenceDiagrams/plans/createPlan-Part2.puml
  docs/uml/sequenceDiagrams/plans/images/createPlan-Part1.png
  docs/uml/sequenceDiagrams/plans/images/createPlan-Part2.png
  docs/uml/sequenceDiagrams/plans/images/listPlan.png
  docs/uml/sequenceDiagrams/plans/listPlan.puml
  docs/uml/sequenceDiagrams/workouts/deleteWorkout-Part1.puml
  docs/uml/sequenceDiagrams/workouts/deleteWorkout-Part2.puml
  docs/uml/sequenceDiagrams/workouts/images/deleteWorkout-Part1.png
  docs/uml/sequenceDiagrams/workouts/images/deleteWorkout-Part2.png
Labels: documentation

#289 Fix image render issue
  docs/team/musfirahe0556596.md
Labels: documentation

#272 Write up on non functional requirements in dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/werkit/UI.java
Labels: documentation

#282 Branch fix bug in help command
  src/main/java/werkit/UI.java
Labels: type.Bug, severity.Low

#283 Branch fix error message problem for schedule feature
  src/main/java/data/schedule/DayList.java
  src/main/java/data/schedule/InvalidScheduleException.java
Labels: type.Bug, severity.Low

#270 Enhance Printing of Messages when Loading Files
  src/main/java/data/exercises/ExerciseList.java
  src/main/java/storage/FileManager.java
  src/main/java/werkit/WerkIt.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, severity.Low

#293 Rename constants to maintain code quality in `PlanCommand.java`
  docs/team/musfirahe0556596.md
  src/main/java/commands/PlanCommand.java
  src/main/java/data/plans/InvalidPlanException.java
  src/main/java/data/plans/PlanList.java
  src/main/java/werkit/Parser.java
Labels: type.Task

#294 Branch standardize seq diagram
  docs/DeveloperGuide.md
  docs/uml/Style.puml
  docs/uml/sequenceDiagrams/schedule/clearAllSchedule.puml
  docs/uml/sequenceDiagrams/schedule/clearSchedule.puml
  docs/uml/sequenceDiagrams/schedule/images/clearAllSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/clearSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/listSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/updateSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/updateScheduleDetails.png
  docs/uml/sequenceDiagrams/schedule/updateSchedule.puml
  docs/uml/sequenceDiagrams/schedule/updateScheduleDetails.puml
  docs/uml/sequenceDiagrams/schedule/viewSchedule.puml
  docs/uml/sequenceDiagrams/workouts/images/listWorkout.png
  docs/uml/sequenceDiagrams/workouts/listWorkouts.puml
Labels: documentation, type.Enhancement

#295 Branch change constants naming
  src/main/java/commands/ScheduleCommand.java
  src/main/java/werkit/Parser.java
Labels: type.Task

#290 DG - Colour Diagrams and Manual Testing Write-Up
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/high-level-diagram/architecture-diagram.puml
  docs/high-level-diagram/architecture_diagram.png
  docs/images/plansTxtDeletePlan.png
  docs/images/plansTxtNewPlans.png
  docs/images/plansTxtWorkoutDeleteCascade.png
  docs/images/scheduleTxtDeleteDay.png
  docs/images/scheduleTxtNewDays.png
  docs/images/scheduleTxtPlanDeleteCascade.png
  docs/images/scheduleTxtWorkoutDeleteCascade.png
  docs/images/workoutsTxtDeleteWorkout.png
  docs/images/workoutsTxtNewWorkouts.png
  docs/images/workoutsTxtUpdateWorkout.png
  docs/team/alanlowzies.md
  docs/uml/Style.puml
  docs/uml/classDiagrams/StorageComponent.puml
  docs/uml/classDiagrams/images/StorageComponent.png
  docs/uml/sequenceDiagrams/miscellaneous/images/obtainAndParseUserInput.png
  docs/uml/sequenceDiagrams/miscellaneous/obtainAndParseUserInput.puml
  docs/uml/sequenceDiagrams/storage/images/loadWorkoutsTxt.png
  docs/uml/sequenceDiagrams/storage/images/rewriteResourceFile.png
  docs/uml/sequenceDiagrams/storage/images/writeNewLineOfData.png
  docs/uml/sequenceDiagrams/storage/loadWorkoutsTxt.puml
  docs/uml/sequenceDiagrams/storage/rewriteResourceFile.puml
  docs/uml/sequenceDiagrams/storage/writeNewLineOfData.puml
  docs/uml/sequenceDiagrams/workouts/CreateAndAddWorkout.puml
  docs/uml/sequenceDiagrams/workouts/CreateWorkout.puml
  docs/uml/sequenceDiagrams/workouts/images/CreateAndAddWorkout.png
  docs/uml/sequenceDiagrams/workouts/images/CreateWorkout.png
Labels: documentation, type.Enhancement

#296 Branch dg manual testing documentation
  docs/DeveloperGuide.md
Labels: documentation

#297 Branch adding dg improvements
  docs/DeveloperGuide.md
Labels: documentation

#300 DG - Group Review Changes
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/workouts/CreateAndAddWorkout.puml
  docs/uml/sequenceDiagrams/workouts/images/CreateAndAddWorkout.png
  docs/uml/sequenceDiagrams/workouts/images/deleteWorkout-Part1.png
Labels: documentation, type.Enhancement

#302 Colouring Diagrams of DG
  docs/DeveloperGuide.md
  docs/uml/classDiagrams/images/logicComponent.png
  docs/uml/classDiagrams/images/workoutRelatedFeatures.png
  docs/uml/classDiagrams/logicComponent.puml
  docs/uml/classDiagrams/workoutRelatedFeatures.puml
  docs/uml/sequenceDiagrams/miscellaneous/logicComponentSD.puml
  docs/uml/sequenceDiagrams/plans/createPlan-Part1.puml
  docs/uml/sequenceDiagrams/plans/createPlan-Part2.puml
  docs/uml/sequenceDiagrams/plans/images/createPlan-Part1.png
  docs/uml/sequenceDiagrams/plans/images/createPlan-Part2.png
  docs/uml/sequenceDiagrams/plans/images/listPlan.png
  docs/uml/sequenceDiagrams/plans/listPlan.puml
  docs/uml/sequenceDiagrams/workouts/deleteWorkout-Part1.puml
  docs/uml/sequenceDiagrams/workouts/deleteWorkout-Part2.puml
  docs/uml/sequenceDiagrams/workouts/images/deleteWorkout-Part2.png
Labels: documentation

#303 Branch reupload colour diagram
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/miscellaneous/images/logicComponentSD.png
Labels: documentation

#277 Refractor `WorkoutList#createAndAddWorkout()`
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/workouts/CreateNewWorkout.puml
  docs/uml/sequenceDiagrams/workouts/CreateWorkout.puml
  docs/uml/sequenceDiagrams/workouts/images/CreateAndAddWorkout.png
  docs/uml/sequenceDiagrams/workouts/images/CreateNewWorkout.png
  docs/uml/sequenceDiagrams/workouts/images/CreateWorkout.png
  src/main/java/commands/WorkoutCommand.java
  src/main/java/data/workouts/WorkoutList.java
  src/main/java/storage/FileManager.java
  src/test/java/commands/PlanCommandTest.java
  src/test/java/commands/ScheduleCommandTest.java
  src/test/java/commands/WorkoutCommandTest.java
  src/test/java/data/plans/PlanListTest.java
  src/test/java/data/schedule/DayListTest.java
  src/test/java/data/workouts/WorkoutListTest.java
Labels: type.Task

#305 Branch dg edit
  docs/DeveloperGuide.md
  docs/uml/classDiagrams/Search.puml
  docs/uml/classDiagrams/exercise.puml
  docs/uml/classDiagrams/images/SearchClass.png
  docs/uml/classDiagrams/images/exercise.png
  docs/uml/sequenceDiagrams/exercises/images/viewExercise.png
  docs/uml/sequenceDiagrams/exercises/viewExercise.puml
  docs/uml/sequenceDiagrams/search/images/searchAll.png
  docs/uml/sequenceDiagrams/search/images/searchExercise.png
  docs/uml/sequenceDiagrams/search/images/searchPlan.png
  docs/uml/sequenceDiagrams/search/images/searchWorkout.png
  docs/uml/sequenceDiagrams/search/searchAll.puml
  docs/uml/sequenceDiagrams/search/searchExercise.puml
  docs/uml/sequenceDiagrams/search/searchPlan.puml
  docs/uml/sequenceDiagrams/search/searchWorkout.puml
  src/main/java/commands/ExerciseCommand.java
  src/main/java/commands/SearchCommand.java
  src/main/java/werkit/Parser.java
  src/main/java/werkit/UI.java
  src/test/java/commands/ExerciseCommandTest.java
  src/test/java/commands/SearchCommandTest.java
Labels: type.Bug, documentation, priority.Medium

#306 Fix Naming Conventions of Constants in `WorkoutCommand.java` and `FileManager.java`
  src/main/java/commands/WorkoutCommand.java
  src/main/java/data/workouts/WorkoutList.java
  src/main/java/storage/FileManager.java
  src/main/java/storage/LogHandler.java
  src/main/java/werkit/Parser.java
  src/main/java/werkit/UI.java
  src/main/java/werkit/WerkIt.java
Labels: type.Task

#301 Update DG
  docs/DeveloperGuide.md
  docs/uml/classDiagrams/PlanRelatedFeatures.puml
  docs/uml/classDiagrams/images/PlanRelatedFeatures.png
  docs/uml/sequenceDiagrams/miscellaneous/ArchitectureSequenceDiagram.puml
  docs/uml/sequenceDiagrams/miscellaneous/images/ArchitectureSequenceDiagram.png
Labels: documentation

#308 Refactor according to prof's comment
  src/main/java/commands/ExerciseCommand.java
  src/main/java/commands/HelpCommand.java
  src/main/java/commands/SearchCommand.java
  src/main/java/werkit/Parser.java
Labels: type.Task

#310 Branch refactor `PlanList#createAndAddPlan()`
  docs/DeveloperGuide.md
  docs/uml/classDiagrams/images/workoutRelatedFeatures.png
  docs/uml/classDiagrams/workoutRelatedFeatures.puml
  docs/uml/sequenceDiagrams/miscellaneous/images/logicComponentSD.png
  docs/uml/sequenceDiagrams/miscellaneous/logicComponentSD.puml
  docs/uml/sequenceDiagrams/plans/createPlan-Part1.puml
  docs/uml/sequenceDiagrams/plans/createPlan-Part2.puml
  docs/uml/sequenceDiagrams/plans/images/createPlan-Part1.png
  docs/uml/sequenceDiagrams/plans/images/createPlan-Part2.png
  src/main/java/commands/PlanCommand.java
  src/main/java/data/plans/PlanList.java
  src/test/java/commands/PlanCommandTest.java
  src/test/java/commands/ScheduleCommandTest.java
  src/test/java/commands/SearchCommandTest.java
  src/test/java/data/plans/PlanListTest.java
  src/test/java/data/schedule/DayListTest.java
Labels: documentation, type.Task

#307 Extract Methods in `Parser#createWorkoutCommand()`
  src/main/java/commands/ExitCommand.java
  src/main/java/commands/HelpCommand.java
  src/main/java/werkit/Parser.java
Labels: type.Task

#314 Modify incorrect description
  docs/DeveloperGuide.md
Labels: documentation

#309 Flatten Arrowhead Code in `WerkIt#startContinuousUserInput()`
  docs/DeveloperGuide.md
  src/main/java/commands/ExitCommand.java
  src/main/java/werkit/WerkIt.java
Labels: documentation, type.Task

#311 DG - Update More References to the Old `WorkoutList#createAndAddWorkout()` Method
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/storage/images/loadWorkoutsTxt.png
  docs/uml/sequenceDiagrams/storage/loadWorkoutsTxt.puml
Labels: documentation

#315 Emphasize target user in UG
  docs/UserGuide.md
Labels: documentation

#317 Update diagrams with parameters
  docs/uml/classDiagrams/Search.puml
  docs/uml/classDiagrams/exercise.puml
  docs/uml/classDiagrams/images/SearchClass.png
  docs/uml/classDiagrams/images/exercise.png
Labels: documentation

#318 Edited Seq Diagram for schedule features
  docs/DeveloperGuide.md
  docs/uml/classDiagrams/ScheduleClass.puml
  docs/uml/classDiagrams/images/scheduleComponent.png
  docs/uml/sequenceDiagrams/schedule/clearAllSchedule.puml
  docs/uml/sequenceDiagrams/schedule/clearSchedule.puml
  docs/uml/sequenceDiagrams/schedule/images/clearAllSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/clearSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/listSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/updateSchedule.png
  docs/uml/sequenceDiagrams/schedule/images/updateScheduleDetails.png
  docs/uml/sequenceDiagrams/schedule/updateSchedule.puml
  docs/uml/sequenceDiagrams/schedule/updateScheduleDetails.puml
  docs/uml/sequenceDiagrams/schedule/viewSchedule.puml
  docs/uml/sequenceDiagrams/workouts/images/listWorkout.png
  docs/uml/sequenceDiagrams/workouts/listWorkouts.puml
Labels: documentation

#319 Add in more junits test for schedule feature
  src/main/java/data/schedule/Day.java
  src/main/java/data/schedule/DayList.java
  src/test/java/commands/ScheduleCommandTest.java
  src/test/java/data/schedule/DayListTest.java
Labels: type.Task

#320 Branch update dg minor
  docs/DeveloperGuide.md
  src/test/java/commands/SearchCommandTest.java
  src/test/java/data/exercises/ExerciseListTest.java
Labels: documentation, type.Task

#321 Add information box
  docs/DeveloperGuide.md
Labels: documentation

#323 New edits to PPP-Emily
  docs/images/ppp/emilysim00/tPCodeDashboard.png
  docs/team/emilysim00.md
Labels: documentation

#324 Fixed error message
  src/main/java/commands/ScheduleCommand.java
  src/main/java/data/schedule/InvalidScheduleException.java
Labels: type.Bug, severity.Low

#326 Edit PPP
  docs/images/ppp/musfirahe0556596/PRReviews.PNG
  docs/images/ppp/musfirahe0556596/tpCodeDashboard.PNG
  docs/images/ppp/musfirahe0556596/tpCommentDashboard.PNG
  docs/team/musfirahe0556596.md
Labels: documentation

#325 Branch update ppp
  docs/images/ppp/a1021492980/tpDashBoard.png
  docs/team/a1021492980.md
Labels: documentation

#322 Write PPP Reflection and Modify DG
  docs/DeveloperGuide.md
  docs/team/alanlowzies.md
  docs/uml/sequenceDiagrams/miscellaneous/images/obtainAndParseUserInput.png
  docs/uml/sequenceDiagrams/miscellaneous/obtainAndParseUserInput.puml
Labels: documentation

#327 Modify PPP to fit page limit
  docs/images/ppp/musfirahe0556596/PRReviews.PNG
  docs/images/ppp/musfirahe0556596/tpCommentDashboard.PNG
  docs/team/musfirahe0556596.md
Labels: documentation

#328 Remove ppp content
  docs/images/ppp/emilysim00/severeBug1.png
  docs/team/emilysim00.md
Labels: documentation

#329 Update PPP
  docs/DeveloperGuide.md
  docs/images/ppp/tianaiyan/tpCodeDashboard.png
  docs/team/tianaiyan.md
  src/main/java/data/plans/PlanList.java
Labels: documentation

#330 Update table of contents for implementation section for DG
  docs/DeveloperGuide.md
Labels: documentation

#331 Branch lessen ppp
  docs/images/ppp/emilysim00/tPCodeDashboard.png
  docs/team/emilysim00.md
Labels: documentation

#334 Enable multiple whitespace in markdown
  docs/DeveloperGuide.md
Labels: documentation

#336 update dg
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/search/images/searchAll.png
  docs/uml/sequenceDiagrams/search/images/searchExercise.png
  docs/uml/sequenceDiagrams/search/images/searchPlan.png
  docs/uml/sequenceDiagrams/search/images/searchWorkout.png
  docs/uml/sequenceDiagrams/search/searchAll.puml
  docs/uml/sequenceDiagrams/search/searchExercise.puml
  docs/uml/sequenceDiagrams/search/searchPlan.puml
  docs/uml/sequenceDiagrams/search/searchWorkout.puml
Labels: documentation

#335 DeveloperGuide.md: Remove extra asterisk
  docs/DeveloperGuide.md
Labels: documentation

#341 Update test case description
  docs/DeveloperGuide.md
Labels: documentation

#337 Branch edit dg
  docs/DeveloperGuide.md
Labels: documentation

#343 DeveloperGuide.md: Edit table in 'Data saving' test instructions
  docs/DeveloperGuide.md
Labels: documentation

#344 Branch edit dg
  docs/DeveloperGuide.md
  docs/uml/classDiagrams/ScheduleClass.puml
  docs/uml/classDiagrams/images/scheduleComponent.png
  docs/uml/sequenceDiagrams/schedule/clearSchedule.puml
  docs/uml/sequenceDiagrams/schedule/images/clearSchedule.png
Labels: documentation

#333 Branch edits to ppp
  docs/team/emilysim00.md
Labels: documentation

#345 Branch edit Sequence Diagram Workout-related features
  docs/DeveloperGuide.md
  docs/uml/classDiagrams/images/workoutRelatedFeatures.png
  docs/uml/classDiagrams/workoutRelatedFeatures.puml
Labels: documentation

#347 Branch fix writing in dg
  docs/DeveloperGuide.md
Labels: documentation

#348 remove symbols
  docs/DeveloperGuide.md
Labels: documentation

#349 UI.java: Update `getUserInput()` to handle system signals Z and C
  src/main/java/werkit/UI.java
Labels: type.Enhancement

#351 Fix JavaDocs
  src/main/java/data/workouts/WorkoutList.java
  src/main/java/storage/FileManager.java
Labels: documentation

#350 Branch fixed java docs
  src/main/java/data/schedule/DayList.java
  src/main/java/werkit/UI.java
Labels: documentation

#352 Fix JavaDocs issues
  src/main/java/commands/SearchCommand.java
  src/main/java/werkit/Parser.java
  src/main/java/werkit/UI.java
Labels: documentation

#353 Modify seq diagram
  docs/uml/sequenceDiagrams/schedule/images/updateScheduleDetails.png
  docs/uml/sequenceDiagrams/schedule/updateScheduleDetails.puml
Labels: type.Enhancement

#354 Update the JavaDocs
  src/main/java/data/workouts/WorkoutList.java
  src/main/java/werkit/UI.java
Labels: documentation

#355 Change to full name for haofeng's PPP
  docs/team/a1021492980.md
Labels: documentation

#356 Change ppp title
  docs/team/tianaiyan.md
Labels: documentation

#357 Fix wrong class name
  docs/team/tianaiyan.md
Labels: documentation

#358 Update UG
  docs/UserGuide.md
Labels: documentation

#359 Ppp emily edits
  docs/team/emilysim00.md
Labels: documentation

#360 Make My PPP More Compact
  docs/team/alanlowzies.md
Labels: documentation

#362 Branch final update
  docs/DeveloperGuide.md
  docs/uml/sequenceDiagrams/search/images/searchAll.png
  docs/uml/sequenceDiagrams/search/images/searchExercise.png
  docs/uml/sequenceDiagrams/search/images/searchPlan.png
  docs/uml/sequenceDiagrams/search/images/searchWorkout.png
  docs/uml/sequenceDiagrams/search/searchAll.puml
  docs/uml/sequenceDiagrams/search/searchExercise.puml
  docs/uml/sequenceDiagrams/search/searchPlan.puml
  docs/uml/sequenceDiagrams/search/searchWorkout.puml
Labels: documentation

#363 Fix broken link on PPP
  docs/team/musfirahe0556596.md
Labels: documentation

#364 Modify word
  docs/team/musfirahe0556596.md
Labels: documentation
